Написал юнит-тесты
sergdenisov/hh-school-2024-unit-testing pull request #1
Opened 2024-12-17 17:32 UTC by sergdenisov

<img width="567" alt="Screenshot 2024-12-17 at 20 31 19" src="https://github.com/user-attachments/assets/a4ce29d5-af36-414c-9f3b-36490d1a6098" />

2024-12-17 21:11 UTC, blackoutks requested changes

2024-12-17 21:11 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +public class LibraryManagerTest {
В JUnit 5 тестовые классы можно не делать `public`, а оставить просто без модификатора доступа.

2024-12-17 21:11 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +    boolean wrongUserBookReturnResult = libraryManager.returnBook("1", "0");
Тут лучше либо разбить на два теста с более говорящими именами, либо сделать через параметризованный тест, т.к., по сути, ты тут проверяешь подряд два очень похожих кейса.

2024-12-17 21:11 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +  })
Сюда бы еще добавить кейс для проверки строгости неравенства `overdueDays < 0`. Т.е. надо сделать так, чтобы если в коде кто-то поменяет знак на `<=`, то хотя бы один тест это поймал.

2024-12-18 09:17 UTC, sergdenisov commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +public class LibraryManagerTest {
Спасибо, убрал.

2024-12-18 09:18 UTC, sergdenisov commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +    boolean wrongUserBookReturnResult = libraryManager.returnBook("1", "0");
Спасибо, сделал параметризованный тест.

2024-12-18 09:18 UTC, sergdenisov commented on src/test/java/ru/hh/school/unittesting/homework/LibraryManagerTest.java
> +  })
Спасибо, добавил.

2024-12-18 11:30 UTC, blackoutks approved these changes

2024-12-18 11:44 UTC, merged